export default {
  app_name: "SharaForms",
  locale: "en",
  locales: { en: "EN" },
  githubAuth: null,
  links: {
    help_url: "https://sharaforms.com/forms/support-form-1zr4yc",
    whatsapp: "https://whatsapp.com/channel/0029VbDNMPnFsn0eE3e08i3Z",
    linkedin: "https://www.linkedin.com/company/sharaforms",
    twitter: "https://x.com/sharaforms",
    zapier_integration:
      "https://zapier.com/developer/public-invite/146950/58db583730cc46b821614468d94c35de/",
    book_onboarding: "https://cal.com/sharaforms/intro-call",
    feature_requests: "https://sharaforms.com/forms/feature-request-form-z7nhxv",
    changelog_url: "https://feedback.sharaforms.com/changelog",
    roadmap: "https://feedback.sharaforms.com/roadmap",
    tech_docs: "https://docs.sharaforms.com",
    api_docs: "https://docs.sharaforms.com",
    self_hosting: "https://docs.sharaforms.com",
    custom_code_docs: "https://docs.sharaforms.com",
    javascript_sdk_docs: "https://docs.sharaforms.com/embedding/javascript-sdk",
    email_setup_docs: "https://docs.sharaforms.com",
    contact_email: "support@sharaforms.com",
  },
}
