FROM node:24-alpine

WORKDIR /app

RUN apk add --no-cache git

COPY ./client/package.json ./client/package-lock.json ./
RUN npm cache clean --force && \
    rm -rf node_modules && \
    npm ci && \
    npm cache clean --force

CMD ["node"]
